Alexcimad/surf-buddy-rental

Gemfile, Gemfile.lock
=> add devise gem

app/models/user.rb, app/views/layouts/application.html.erb, config/environments/development.rb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20220129143841_devise_create_users.rb, db/schema.rb, test/models/user_test.rb
=> Generate user

Gemfile.lock, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/views/layouts/application.html.erb, app/views/shared/_footer.html.erb
=> footer created

app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_index.scss, app/views/pages/home.html.erb
=> Prepare Cards

Gemfile, Gemfile.lock, app/models/offer.rb, app/models/user.rb, db/seeds.rb
Seed creation of 10 offer objects
=> Seeds created

app/models/user.rb, db/seeds.rb
=> correction regarding seed creation

app/views/offers/index.html.erb
=> Add index view for Offers

app/assets/stylesheets/components/_container.scss
=> add container component

app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/config/_colors.scss, app/views/offers/index.html.erb
Add colors and style for the cards and project
=> :lipstick: Add colors and style

app/controllers/bookings_controller.rb, app/models/booking.rb, app/views/bookings/new.html.erb, app/views/offers/show.html.erb, config/routes.rb, test/controllers/bookings_controller_test.rb
Creation of bookings controller in order to create bookings
=> Bookings creation

.gitignore, app/models/offer.rb, app/views/offers/index.html.erb, db/seeds.rb
=> Cloudinary setup theo

db/seeds.rb
=> change image seed

app/views/devise/registrations/edit.html.erb, app/views/shared/_footer.html.erb, app/views/shared/_navbar.html.erb
=> Add menu with bookings

app/assets/stylesheets/components/_cards.scss, app/views/my/bookings/index.html.erb
=> add style to bookings

app/controllers/application_controller.rb, app/models/user.rb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/shared/_navbar.html.erb
=> add profile picture

db/seeds.rb
=> seedcreation

app/assets/stylesheets/components/_cards.scss, app/views/offers/edit.html.erb
=> update edit et carroussel

app/assets/stylesheets/pages/_home.scss, app/controllers/pages_controller.rb, app/views/pages/home.html.erb
=> Edit Homepage

app/views/offers/show.html.erb, app/views/pages/home.html.erb
=> update video and bookings

app/controllers/pages_controller.rb, app/views/pages/home.html.erb
=> Add stats to homepage

app/controllers/bookings_controller.rb, app/controllers/my/offers_controller.rb, app/views/my/offers/index.html.erb, app/views/shared/_navbar.html.erb, config/routes.rb, test/controllers/my/offers_controller_test.rb
- Add my boards in menu
- Add controller my/offers
- Add view my/offers
- Add routes offers in my
=> Add my boards in menu

app/views/bookings/new.html.erb, app/views/my/offers/index.html.erb, app/views/offers/show.html.erb
=> add show offers

app/assets/stylesheets/pages/_index.scss, app/views/offers/index.html.erb
=> Add map to the right

app/assets/stylesheets/components/_search.scss, app/assets/stylesheets/pages/_index.scss, app/views/offers/index.html.erb
=> Style search

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_cards.scss, app/views/offers/_show.html.erb
- Delete links (edit and delete) in modal
- Custom modal (CTA colors, close btn and image)
=> delete link in modal + custom modal

app/assets/stylesheets/components/_bookings.scss, app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/pages/_booking.scss, app/assets/stylesheets/pages/_index.scss, app/views/bookings/_new.html.erb, app/views/bookings/new.html.erb
=> custom bookings

app/assets/stylesheets/components/_breadcrumb.scss, app/assets/stylesheets/components/_index.scss, app/controllers/bookings_controller.rb, app/views/bookings/new.html.erb, app/views/shared/_breadcrumb.html.erb
=> add breadcrumb

app/assets/stylesheets/pages/_booking.scss, app/views/bookings/new.html.erb
=> fix booking

app/assets/stylesheets/components/_footer.scss, app/controllers/offers_controller.rb, app/views/shared/_form_create_update_offer.html.erb
fix redirection to my_offers in edit and add board
=> fix redirection to my_offers in edit and add board
